In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, confusion_matrix, classification_report

In [31]:
df = pd.read_csv('Credit')
df.head(5)

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,14.891,3606.0,283.0,2.0,34.0,11.0,Male,No,Yes,Caucasian,333.0
1,2,106.025,6645.0,483.0,3.0,82.0,15.0,Female,Yes,Yes,Asian,903.0
2,3,104.593,7075.0,514.0,4.0,71.0,11.0,Male,No,No,Asian,580.0
3,4,148.924,9504.0,681.0,3.0,36.0,11.0,Female,No,No,Asian,964.0
4,5,55.882,4897.0,357.0,2.0,68.0,16.0,Male,No,Yes,Caucasian,331.0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 12 columns):
Unnamed: 0    401 non-null object
Income        400 non-null float64
Limit         400 non-null float64
Rating        400 non-null float64
Cards         400 non-null float64
Age           400 non-null float64
Education     400 non-null float64
Gender        400 non-null object
Student       400 non-null object
Married       400 non-null object
Ethnicity     399 non-null object
Balance       400 non-null float64
dtypes: float64(7), object(5)
memory usage: 37.7+ KB

In [33]:
df.keys()

Index(['Unnamed: 0', 'Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education',
       'Gender', 'Student', 'Married', 'Ethnicity', 'Balance'],
      dtype='object')

In [34]:
df.isnull()

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
371,False,False,False,False,False,False,False,False,False,False,False,False
372,False,False,False,False,False,False,False,False,False,False,False,False
373,False,False,False,False,False,False,False,False,False,False,False,False
374,False,False,False,False,False,False,False,False,False,False,False,False
375,False,False,False,False,False,False,False,False,False,False,False,False
376,False,False,False,False,False,False,False,False,False,False,False,False
377,False,False,False,False,False,False,False,False,False,False,False,False
378,False,False,False,False,False,False,False,False,False,False,False,False
379,False,False,False,False,False,False,False,False,False,False,False,False
380,False,False,False,False,False,False,False,False,False,False,False,False
381,False,False,False,False,False,False,False,False,False,False,False,False
382,False,False,False,False,False,False,False,False,False,False,False,False
383,False,False,False,False,False,False,False,False,False,False,False,False
384,False,False,False,False,False,False,False,False,False,False,False,False
385,False,False,False,False,False,False,False,False,False,False,False,False
386,False,False,False,False,False,False,False,False,False,False,False,False
387,False,False,False,False,False,False,False,False,False,False,False,False
388,False,False,False,False,False,False,False,False,False,False,False,False
389,False,False,False,False,False,False,False,False,False,False,False,False
390,False,False,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False,False,False,False
398,False,False,False,False,False,False,False,False,False,False,False,False
399,False,False,False,False,False,False,False,False,False,False,False,False
400,False,True,True,True,True,True,True,True,True,True,True,True

In [35]:
df1 = df.dropna()

In [36]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 399 entries, 0 to 399
Data columns (total 12 columns):
Unnamed: 0    399 non-null object
Income        399 non-null float64
Limit         399 non-null float64
Rating        399 non-null float64
Cards         399 non-null float64
Age           399 non-null float64
Education     399 non-null float64
Gender        399 non-null object
Student       399 non-null object
Married       399 non-null object
Ethnicity     399 non-null object
Balance       399 non-null float64
dtypes: float64(7), object(5)
memory usage: 40.5+ KB

In [37]:
gender = pd.get_dummies(df1['Gender'],drop_first=True)
student = pd.get_dummies(df1['Student'],drop_first=True)
married = pd.get_dummies(df1['Married'],drop_first=True)
ethnicity = pd.get_dummies(df1['Ethnicity'],drop_first=True)

In [38]:
df2 = pd.concat([df1,gender,student,married,ethnicity],axis=1)

In [39]:
df2.head()

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance,Male,Yes,Yes,Asian,Caucasian
0,1,14.891,3606.0,283.0,2.0,34.0,11.0,Male,No,Yes,Caucasian,333.0,1,0,1,0,1
1,2,106.025,6645.0,483.0,3.0,82.0,15.0,Female,Yes,Yes,Asian,903.0,0,1,1,1,0
2,3,104.593,7075.0,514.0,4.0,71.0,11.0,Male,No,No,Asian,580.0,1,0,0,1,0
3,4,148.924,9504.0,681.0,3.0,36.0,11.0,Female,No,No,Asian,964.0,0,0,0,1,0
4,5,55.882,4897.0,357.0,2.0,68.0,16.0,Male,No,Yes,Caucasian,331.0,1,0,1,0,1

In [42]:
X = df2.iloc[:,[0,1,3,4,5,6,11,12,13,14,15,16]].values
y = df2.iloc[:,2].values

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)

In [44]:
lr = LinearRegression()

In [45]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
y_pred = lr.predict(X_test)

In [50]:
print(r2_score(y_test,y_pred))

0.9970273069611009