In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,r2_score,classification_report

In [2]:
df = pd.read_csv('Heart.csv')
df.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
Unnamed: 0    303 non-null int64
Age           303 non-null int64
Sex           303 non-null int64
ChestPain     303 non-null object
RestBP        303 non-null int64
Chol          303 non-null int64
Fbs           303 non-null int64
RestECG       303 non-null int64
MaxHR         303 non-null int64
ExAng         303 non-null int64
Oldpeak       303 non-null float64
Slope         303 non-null int64
Ca            299 non-null float64
Thal          301 non-null object
AHD           303 non-null object
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB

In [4]:
df1 = df.fillna(0)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
Unnamed: 0    303 non-null int64
Age           303 non-null int64
Sex           303 non-null int64
ChestPain     303 non-null object
RestBP        303 non-null int64
Chol          303 non-null int64
Fbs           303 non-null int64
RestECG       303 non-null int64
MaxHR         303 non-null int64
ExAng         303 non-null int64
Oldpeak       303 non-null float64
Slope         303 non-null int64
Ca            303 non-null float64
Thal          303 non-null object
AHD           303 non-null object
dtypes: float64(2), int64(10), object(3)
memory usage: 35.6+ KB

In [6]:
df1.keys()

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [7]:
df1.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [8]:
chestpain = pd.get_dummies(df1['ChestPain'],drop_first=True)
thal = pd.get_dummies(df1['Thal'],drop_first=True)
ahd = pd.get_dummies(df1['AHD'],drop_first=True)
df2 = pd.concat([df1,chestpain,thal,ahd],axis=1)

In [9]:
df2.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,...,Ca,Thal,AHD,nonanginal,nontypical,typical,fixed,normal,reversable,Yes
0,1,63,1,typical,145,233,1,2,150,0,...,0.0,fixed,No,0,0,1,1,0,0,0
1,2,67,1,asymptomatic,160,286,0,2,108,1,...,3.0,normal,Yes,0,0,0,0,1,0,1
2,3,67,1,asymptomatic,120,229,0,2,129,1,...,2.0,reversable,Yes,0,0,0,0,0,1,1
3,4,37,1,nonanginal,130,250,0,0,187,0,...,0.0,normal,No,1,0,0,0,1,0,0
4,5,41,0,nontypical,130,204,0,2,172,0,...,0.0,normal,No,0,1,0,0,1,0,0

In [10]:
df2.drop(['Thal','ChestPain','AHD'],axis=1,inplace=True)

In [11]:
df2.head()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,nonanginal,nontypical,typical,fixed,normal,reversable,Yes
0,1,63,1,145,233,1,2,150,0,2.3,3,0.0,0,0,1,1,0,0,0
1,2,67,1,160,286,0,2,108,1,1.5,2,3.0,0,0,0,0,1,0,1
2,3,67,1,120,229,0,2,129,1,2.6,2,2.0,0,0,0,0,0,1,1
3,4,37,1,130,250,0,0,187,0,3.5,3,0.0,1,0,0,0,1,0,0
4,5,41,0,130,204,0,2,172,0,1.4,1,0.0,0,1,0,0,1,0,0

In [12]:
X = df2.drop('Yes',axis=1)

In [13]:
y = df2.iloc[:,-1]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
lrr = LogisticRegression()

In [16]:
lrr.fit(X_train,y_train)

C:\Users\tirum\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
y_pred = lrr.predict(X_test)

In [20]:
print(confusion_matrix(y_test,y_pred))

[[30  4]
 [ 7 20]]

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.85        34
           1       0.83      0.74      0.78        27

    accuracy                           0.82        61
   macro avg       0.82      0.81      0.81        61
weighted avg       0.82      0.82      0.82        61